//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamBuilding
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrjtClasses
    {
        public int ClPrjtId { get; set; }
        public int ClClassId { get; set; }
        public string ClPeopleNeeded { get; set; }
    
        public virtual Classes Classes { get; set; }
        public virtual Projects Projects { get; set; }
    }
}
